name: org-trufflehog

on:
  workflow_dispatch:
  schedule:
    - cron: "23 9 14 * *"  # monthly (minute-safe policy)

permissions: read-all

concurrency:
  group: org-trufflehog-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trufflehog:
    uses: gr8monk3ys/github/.github/workflows/reusable-trufflehog.yml@4a306a94d72d10b8d7835d697521a469fc6deab1
