name: org-gitleaks

on:
  workflow_dispatch:
  schedule:
    - cron: "23 9 14 * *"  # monthly (minute-safe policy)

permissions: read-all

jobs:
  gitleaks:
    uses: gr8monk3ys/github/.github/workflows/reusable-gitleaks.yml@4a306a94d72d10b8d7835d697521a469fc6deab1
