name: org-release-please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    uses: gr8monk3ys/github/.github/workflows/reusable-release-please.yml@88552ca2cc9623b35675170019ecf2db9ea458ea
