name: org-ci-tests

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  ci-tests:
    uses: gr8monk3ys/github/.github/workflows/reusable-ci-tests-minimum.yml
