name: security-baseline

on:
  push:
    branches:
      - "**"
  pull_request:

permissions: read-all

jobs:
  security-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Baseline CI check
        run: |
          echo "Security baseline workflow is active"
